"""Pydantic V2 validation layer.

Each module mirrors an ORM model in :mod:`app.models` and exposes the
``*Base / *Create / *Update / *Read`` quartet that the FastAPI routers use
for request/response validation. Schemas never talk to SQLAlchemy
directly — the routers translate to/from ORM objects.
"""

from app.schemas.auth import (
    EmailVerificationRequest,
    EmailVerificationResendResponse,
    GoogleCallbackResponse,
    LoginRequest,
    LoginResponse,
    MessageResponse,
    PasswordChangeRequest,
    PasswordRecoverRequest,
    PasswordRecoverResponse,
    PasswordResetRequest,
    RefreshRequest,
    RefreshResponse,
    RegisterResponse,
    TokenEnvelope,
    TokenPair,
)
from app.schemas.brand_kit import (
    BrandKitBase,
    BrandKitCreate,
    BrandKitLogoResponse,
    BrandKitRead,
    BrandKitUpdate,
    validate_hex_color,
)
from app.schemas.integration import (
    ApiKeyCreate,
    ApiKeyCreated,
    ApiKeyRead,
    ApiKeyUpdate,
    EventType,
    IntegrationLogRead,
    IntegrationsOverview,
    ProviderInfo,
    ProviderListResponse,
    ThirdPartyIntegrationCreate,
    ThirdPartyIntegrationRead,
    ThirdPartyIntegrationUpdate,
    WebhookCreate,
    WebhookCreated,
    WebhookRead,
    WebhookTestResult,
    WebhookUpdate,
)
from app.schemas.invitation import (
    InvitationAcceptResponse,
    InvitationCreate,
    InvitationPublic,
    InvitationRead,
)
from app.schemas.membership import (
    MembershipCreate,
    MembershipRead,
    MembershipUpdate,
    TransferOwnership,
)
from app.schemas.organization import (
    OrganizationCreate,
    OrganizationRead,
    OrganizationSummary,
    OrganizationUpdate,
    validate_slug,
)
from app.schemas.user import (
    UserCreate,
    UserPublic,
    UserRead,
    UserUpdate,
    UsernameStr,
    validate_username,
)

__all__ = [
    "ApiKeyCreate",
    "ApiKeyCreated",
    "ApiKeyRead",
    "ApiKeyUpdate",
    "BrandKitBase",
    "BrandKitCreate",
    "BrandKitLogoResponse",
    "BrandKitRead",
    "BrandKitUpdate",
    "EmailVerificationRequest",
    "EmailVerificationResendResponse",
    "EventType",
    "GoogleCallbackResponse",
    "IntegrationLogRead",
    "IntegrationsOverview",
    "InvitationAcceptResponse",
    "InvitationCreate",
    "InvitationPublic",
    "InvitationRead",
    "LoginRequest",
    "LoginResponse",
    "MembershipCreate",
    "MembershipRead",
    "MembershipUpdate",
    "MessageResponse",
    "OrganizationCreate",
    "OrganizationRead",
    "OrganizationSummary",
    "OrganizationUpdate",
    "PasswordChangeRequest",
    "PasswordRecoverRequest",
    "PasswordRecoverResponse",
    "PasswordResetRequest",
    "ProviderInfo",
    "ProviderListResponse",
    "RefreshRequest",
    "RefreshResponse",
    "RegisterResponse",
    "ThirdPartyIntegrationCreate",
    "ThirdPartyIntegrationRead",
    "ThirdPartyIntegrationUpdate",
    "TokenEnvelope",
    "TokenPair",
    "TransferOwnership",
    "UserCreate",
    "UserPublic",
    "UserRead",
    "UserUpdate",
    "UsernameStr",
    "WebhookCreate",
    "WebhookCreated",
    "WebhookRead",
    "WebhookTestResult",
    "WebhookUpdate",
    "validate_hex_color",
    "validate_slug",
    "validate_username",
]
